%YAML:1.0
# camera

camera.cx: 325.5
camera.cy: 253.5
camera.fx: 518.0
camera.fy: 519.0
camera.scale: 1000.0



rbg_image_path: "/home/Andy/my_workspace/Dataset/TUM/RGBD_dataset/rgb_png/"
depth_image_path: "/home/Andy/my_workspace/Dataset/TUM/RGBD_dataset/depth_png/"

start_index: 1
end_index: 700


good_match_threshold: 4

min_inliers: 5

max_norm: 0.3

keyframe_threshold: 0.1
max_norm_lp: 2.0
# Loop closure
check_loop_closure: 1
nearby_loops: 5
random_loops: 5

